name: Bug report
description: Report a problem you're having with the mod.
title: "Bug report"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: "Bug description:"
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: "Reproduction steps"
      description: "How do you trigger this bug?"
      placeholder: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: false

  - type: input
    attributes:
      label: Mod version
      placeholder: e.g. 1.0
    validations:
      required: true

  - type: input
    attributes:
      label: CSP version
      placeholder: e.g. 0.3.0p212
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thank you for the report!